apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 519763206721.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
