apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: 519763206721.dkr.ecr.ap-south-1.amazonaws.com/mongo:latest
        ports:
        - containerPort: 27017