apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streaming-service
  template:
    metadata:
      labels:
        app: streaming-service
    spec:
      containers:
      - name: streaming-service
        image: 519763206721.dkr.ecr.ap-south-1.amazonaws.com/streaming-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: MONGO_URI
          value: mongodb://mongo:27017/streamdb
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: streaming-app-secrets
              key: JWT_SECRET
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: streaming-app-secrets
              key: AWS_REGION
        - name: AWS_S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: streaming-app-secrets
              key: AWS_S3_BUCKET
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: streaming-app-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: streaming-app-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_CDN_URL
          valueFrom:
            secretKeyRef:
              name: streaming-app-secrets
              key: AWS_CDN_URL
              optional: true
